Code with the topic : Odds and Odds ratio

#Description:
#This model aims to explain the use of odds and odds ratio in code, practically their structure and function.

#Technologies used:
#Pandas
#Numpy
#Python
#Visual Studio Code
#Jupyter Notebook

#Methods used:
#Logistic Regression

#How to used the code:
We will use this code as a basis for understanding the binary code probabilities of each variable

What does this code do?

This code uses a logistic regression model to analyze how certain variables (age, weight, and smoking status) influence the likelihood of a person developing a disease.

In [23]:
#We import the libraries

import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np

In [24]:
#We read the data 
datos = pd.read_csv("datos_salud.csv")

In [25]:
datos.head()

   Edad  Peso  Fumador  Enfermedad
0    27    70        0           0
1    30    80        1           1
2    45    85        1           1
3    50    90        1           1
4    23    65        0           0

In [26]:
datos.describe()

            Edad       Peso    Fumador  Enfermedad
count  15.000000  15.000000  15.000000   15.000000
mean   40.466667  80.400000   0.600000    0.533333
std    11.115412   9.302841   0.507093    0.516398
min    23.000000  65.000000   0.000000    0.000000
25%    31.500000  73.500000   0.000000    0.000000
50%    40.000000  80.000000   1.000000    1.000000
75%    49.000000  88.500000   1.000000    1.000000
max    60.000000  95.000000   1.000000    1.000000

In [27]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Edad        15 non-null     int64
 1   Peso        15 non-null     int64
 2   Fumador     15 non-null     int64
 3   Enfermedad  15 non-null     int64
dtypes: int64(4)
memory usage: 612.0 bytes

In [ ]:
#We use columns to avoid mistakes when writing variables
datos.columns

Index(['Edad', 'Peso', 'Fumador', 'Enfermedad'], dtype='object')

In [ ]:
#We define X and Y by placing the variables
X = datos[["Edad","Peso","Fumador"]]
Y = datos["Enfermedad"]

In [ ]:
#we create the model and we train it
Modelo = LogisticRegression()
Modelo.fit(X,Y)

c:\Users\Selene\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [31]:
#Coefficients
coeficientes = Modelo.coef_[0]
variables = X.columns

In [32]:
print("==Coefficients==")
for var,coef in zip(variables,coeficientes):
    print(f"{var}: {coef:4f}")

==Coefficients==
Edad: -0.190584
Peso: 0.995205
Fumador: 0.231998

In [ ]:

#We calculate Odds Ratio
#Odds Ratio is the comparison between two groups

#Odds ratio measures how a one-unit increase in a variable
#affects the odds of the outcome


odds_ratio = np.exp(coeficientes)

In [34]:
print("==ODDS RATIO==")
for var,or_val in zip(variables,odds_ratio):
    print(f"{var}: {or_val:.4f}")

==ODDS RATIO==
Edad: 0.8265
Peso: 2.7053
Fumador: 1.2611

In [35]:
#Probabilidades predichas
probabilidades = Modelo.predict_proba(X)[:,1]

In [ ]:
#We calculate Odds:

#Ratio means how likely something is to happen and how likely it is that something will not happen
#Odds = 1 → 50% probability
#Odds > 1 → more likely to occur
#Odds < 1 → less likely
odds = probabilidades / (1-probabilidades)

In [38]:
print("\n==Odds Example==")
for i in range(5):
    print(f"Persona {i+1}: Prob={probabilidades[i]:.4f}-> odds={odds[i]:.4f}")

==Odds Example==
Persona 1: Prob=0.0006-> odds=0.0006
Persona 2: Prob=0.9001-> odds=9.0126
Persona 3: Prob=0.9868-> odds=74.8799
Persona 4: Prob=0.9998-> odds=4183.8563
Persona 5: Prob=0.0000-> odds=0.0000

In [ ]:
#What the data want to tell us ?

#The data already collected gives us valuable information, since if the odds are greater than 5 there is a higher probability that people will get sick, 
# and conversely,if they are less than 5 there is a lower probability that these people will get sick.