#Code with the topic: Saturated Model and Deviance

#Objective
#Evaluate the performance of a logistic regression model using deviance.

#What is Deviance?
#Deviance measures how well a model fits the data. Lower deviance indicates a better #fit.

#Saturated Model
#A saturated model perfectly fits the data and has the minimum possible deviance.

#Technologies used:

#Pandas
#Python
#Jupyter notebook 
#statsmodels
#Visual studio Code

#How to use the code:

#We will use this code as an example of the coding structure of a saturated model and deviance

#Problem Statement:
#We want to determine whether our statistical model performs well when trained.

In [1]:
#We import libraries
import pandas as pd
import statsmodels.api as sm

In [2]:
#Load the dataset
data = pd.read_csv("Satured_model_and_deviance.csv")

In [3]:
#Preview our data
data.head()

   Age  Income  Buy
0   25    2000    0
1   30    3000    0
2   35    4000    1
3   40    5000    1
4   45    5000    1

In [4]:
#data information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     6 non-null      int64
 1   Income  6 non-null      int64
 2   Buy     6 non-null      int64
dtypes: int64(3)
memory usage: 272.0 bytes

In [ ]:
#Statistical summary
data.describe()

             Age       Income       Buy
count   6.000000     6.000000  6.000000
mean   37.500000  4333.333333  0.666667
std     9.354143  1751.190072  0.516398
min    25.000000  2000.000000  0.000000
25%    31.250000  3250.000000  0.250000
50%    37.500000  4500.000000  1.000000
75%    43.750000  5000.000000  1.000000
max    50.000000  7000.000000  1.000000

In [6]:
#We use columns to do not make mistakes defining 

data.columns

Index(['Age', 'Income', 'Buy'], dtype='object')

In [ ]:
#Feature selection
X = data[["Age","Income"]]
X = sm.add_constant(X) #add Intercept
Y = data["Buy"]

In [8]:
#Logistic regression model (GLM)
model = sm.GLM(Y,X,family=sm.families.Binomial())
result =model.fit()

c:\Users\Selene\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
c:\Users\Selene\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
c:\Users\Selene\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

In [9]:
#Model summary
print(result.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                    Buy   No. Observations:                    6
Model:                            GLM   Df Residuals:                        3
Model Family:                Binomial   Df Model:                            2
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -2.1966e-09
Date:                Thu, 09 Apr 2026   Deviance:                   4.3932e-09
Time:                        20:52:34   Pearson chi2:                 2.20e-09
No. Iterations:                    22   Pseudo R-squ. (CS):             0.7200
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -29.6893   2.45e+05     -0.000      1.000    -4.8e+05     4.8e+05
Age           -7.6669   1.78e+04     -0.000      1.000    -3.5e+04     3.5e+04
Income         0.0797    103.346      0.001      0.999    -202.474     202.633
==============================================================================

In [10]:
## Deviance analysis
print(f"Deviance: {result.deviance}")
print(f"Null Deviance: {result.null_deviance}")

Deviance: 4.393228889482504e-09
Null Deviance: 7.638170019537754

#Interpretation
#The model deviance is lower than the null deviance, indicating that
#the model provides a better fit than a model with no predictors.